<?php

namespace App\Command;

use App\Enum\TagRole;
use App\Repository\TagRepository;
use App\Service\TagGovernance;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(name: 'app:tag-noise-report', description: 'Diagnostique les tags auto-generes bruyants et peut les desactiver prudemment.')]
class TagNoiseReportCommand extends Command
{
    public function __construct(
        private readonly TagRepository $tagRepository,
        private readonly TagGovernance $tagGovernance,
        private readonly EntityManagerInterface $entityManager,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->addOption('apply', null, InputOption::VALUE_NONE, 'Desactive les stop-tags auto-generes trouves.');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $apply = (bool) $input->getOption('apply');
        $rows = [];
        $updated = 0;

        foreach ($this->tagGovernance->stopTags() as $slug) {
            $tag = $this->tagRepository->findOneBySlug($slug);
            if ($tag === null) {
                continue;
            }

            $rows[] = [
                $tag->getSlug(),
                $tag->getName(),
                $tag->getRole()->label(),
                $tag->isActive() ? 'oui' : 'non',
                $tag->isAutoGenerated() ? 'oui' : 'non',
            ];

            if ($apply && $tag->isAutoGenerated()) {
                $tag
                    ->setRole(TagRole::Noise)
                    ->setIsActive(false)
                    ->setIsInterestRelated(false)
                    ->setNotes(trim(((string) $tag->getNotes())."\nDesactive par app:tag-noise-report --apply."));
                ++$updated;
            }
        }

        $io->title('Diagnostic tags bruit');
        $io->table(['Slug', 'Nom', 'Role', 'Actif', 'Auto'], $rows);

        if ($apply) {
            $this->entityManager->flush();
            $io->success(sprintf('%d tag(s) auto-generes marques comme bruit/inactifs.', $updated));
        } else {
            $io->note('Dry-run uniquement. Ajoute --apply pour desactiver les stop-tags auto-generes.');
        }

        return Command::SUCCESS;
    }
}
