<?php

namespace App\Controller;

use App\Entity\Tag;
use App\Enum\TagRole;
use App\Form\TagType;
use App\Repository\TagRepository;
use App\Service\ArrayPaginator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/tags')]
class AdminTagController extends AbstractController
{
    #[Route('', name: 'app_admin_tag_index', methods: ['GET'])]
    public function index(Request $request, TagRepository $tagRepository, ArrayPaginator $arrayPaginator): Response
    {
        [$tags, $pagination] = $arrayPaginator->paginate($request, $tagRepository->findAllOrdered(), '25');

        return $this->render('admin/tag/index.html.twig', [
            'tags' => $tags,
            'pagination' => $pagination,
            'pager_route' => 'app_admin_tag_index',
            'title' => 'Tags',
            'intro' => "Tags metier utilises pour la detection, les filtres et l'enrichissement progressif.",
        ]);
    }

    #[Route('/interest', name: 'app_admin_tag_interest', methods: ['GET'])]
    public function interest(Request $request, TagRepository $tagRepository, ArrayPaginator $arrayPaginator): Response
    {
        [$tags, $pagination] = $arrayPaginator->paginate($request, $tagRepository->findActiveInterestRelated(), '25');

        return $this->render('admin/tag/index.html.twig', [
            'tags' => $tags,
            'pagination' => $pagination,
            'pager_route' => 'app_admin_tag_interest',
            'title' => "Tags actifs lies aux centres d'interet",
            'intro' => "Tags actifs qui renforcent directement l'analyse d'interet.",
        ]);
    }

    #[Route('/auto-generated', name: 'app_admin_tag_auto_generated', methods: ['GET'])]
    public function autoGenerated(Request $request, TagRepository $tagRepository, ArrayPaginator $arrayPaginator): Response
    {
        [$tags, $pagination] = $arrayPaginator->paginate($request, $tagRepository->findAutoGeneratedPending(), '25');

        return $this->render('admin/tag/index.html.twig', [
            'tags' => $tags,
            'pagination' => $pagination,
            'pager_route' => 'app_admin_tag_auto_generated',
            'title' => 'Tags auto-generes a valider',
            'intro' => "Tags proposes automatiquement, inactifs tant qu'ils ne sont pas valides.",
        ]);
    }

    #[Route('/noise', name: 'app_admin_tag_noise', methods: ['GET'])]
    public function noise(Request $request, TagRepository $tagRepository, ArrayPaginator $arrayPaginator): Response
    {
        [$tags, $pagination] = $arrayPaginator->paginate($request, $tagRepository->findByRole(TagRole::Noise), '25');

        return $this->render('admin/tag/index.html.twig', [
            'tags' => $tags,
            'pagination' => $pagination,
            'pager_route' => 'app_admin_tag_noise',
            'title' => 'Tags bruit',
            'intro' => "Tags identifies comme bruit editorial ou contexte non exploitable.",
        ]);
    }

    #[Route('/new', name: 'app_admin_tag_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $tag = new Tag();
        $form = $this->createForm(TagType::class, $tag);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($tag);
            $entityManager->flush();
            $this->addFlash('success', 'Tag cree.');

            return $this->redirectToRoute('app_admin_tag_index');
        }

        return $this->render('admin/tag/form.html.twig', [
            'tag' => $tag,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_tag_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Tag $tag, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TagType::class, $tag);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $this->addFlash('success', 'Tag mis a jour.');

            return $this->redirectToRoute('app_admin_tag_index');
        }

        return $this->render('admin/tag/form.html.twig', [
            'tag' => $tag,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/disable', name: 'app_admin_tag_disable', methods: ['POST'])]
    public function disable(Request $request, Tag $tag, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('disable_tag_'.$tag->getId(), (string) $request->request->get('_token'))) {
            $tag->setIsActive(false);
            $entityManager->flush();
            $this->addFlash('success', 'Tag desactive.');
        }

        return $this->redirectToRoute('app_admin_tag_index');
    }

    #[Route('/{id}/validate', name: 'app_admin_tag_validate', methods: ['POST'])]
    public function validateTag(Request $request, Tag $tag, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('validate_tag_'.$tag->getId(), (string) $request->request->get('_token'))) {
            $tag
                ->setIsActive(true)
                ->setIsInterestRelated(true)
                ->setRole(TagRole::Pivot)
                ->setNotes(trim(((string) $tag->getNotes())."\nValide depuis l'Admin comme tag lie au profil d'interet."));
            $entityManager->flush();
            $this->addFlash('success', 'Tag valide et rattache au profil d interet.');
        }

        return $this->redirectToRoute('app_admin_tag_auto_generated');
    }
}
