<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260504140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add analysis correction log';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE analysis_correction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entry_id INT DEFAULT NULL, field_name VARCHAR(40) NOT NULL, old_value JSON DEFAULT NULL, new_value JSON DEFAULT NULL, reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ANALYSIS_CORRECTION_ENTRY ON analysis_correction (entry_id)');
        $this->addSql('CREATE INDEX IDX_ANALYSIS_CORRECTION_FIELD ON analysis_correction (field_name)');
        $this->addSql('ALTER TABLE analysis_correction ADD CONSTRAINT FK_ANALYSIS_CORRECTION_ENTRY FOREIGN KEY (entry_id) REFERENCES entry (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE analysis_correction DROP CONSTRAINT FK_ANALYSIS_CORRECTION_ENTRY');
        $this->addSql('DROP TABLE analysis_correction');
    }
}
