<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260503120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add RSS import metadata and import run history.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE source ADD fetch_mode VARCHAR(255) NOT NULL DEFAULT \'manual\'');
        $this->addSql('ALTER TABLE source ALTER fetch_mode DROP DEFAULT');
        $this->addSql('ALTER TABLE source ADD feed_url VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE source ADD last_fetched_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE source ADD last_success_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE source ADD last_error_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE source ADD last_error_message TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE entry ADD external_id VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE entry ADD canonical_url VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE entry ADD published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE entry ADD imported_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE entry ADD raw_payload JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE entry ADD source_hash VARCHAR(64) DEFAULT NULL');
        $this->addSql('CREATE TABLE import_run (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_id INT NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(255) NOT NULL, fetched_count INT NOT NULL, created_count INT NOT NULL, skipped_count INT NOT NULL, error_message TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C41B0440953C1C61 ON import_run (source_id)');
        $this->addSql('ALTER TABLE import_run ADD CONSTRAINT FK_C41B0440953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE import_run DROP CONSTRAINT FK_C41B0440953C1C61');
        $this->addSql('DROP TABLE import_run');
        $this->addSql('ALTER TABLE entry DROP external_id');
        $this->addSql('ALTER TABLE entry DROP canonical_url');
        $this->addSql('ALTER TABLE entry DROP published_at');
        $this->addSql('ALTER TABLE entry DROP imported_at');
        $this->addSql('ALTER TABLE entry DROP raw_payload');
        $this->addSql('ALTER TABLE entry DROP source_hash');
        $this->addSql('ALTER TABLE source DROP fetch_mode');
        $this->addSql('ALTER TABLE source DROP feed_url');
        $this->addSql('ALTER TABLE source DROP last_fetched_at');
        $this->addSql('ALTER TABLE source DROP last_success_at');
        $this->addSql('ALTER TABLE source DROP last_error_at');
        $this->addSql('ALTER TABLE source DROP last_error_message');
    }
}
