<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260503220000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add admin reference tables, tag entity and draft review flags';
    }

    public function up(Schema $schema): void
    {
        $uniqueIndexes = [
            'media_type_reference' => 'UNIQ_BB50FC43989D9B62',
            'source_type_reference' => 'UNIQ_B91C64A6989D9B62',
            'fetch_mode_reference' => 'UNIQ_9BCE860C989D9B62',
            'decision_type_reference' => 'UNIQ_CA3F9F26989D9B62',
            'clickbait_level_reference' => 'UNIQ_86E4B35A989D9B62',
            'analysis_language_reference' => 'UNIQ_626354AF989D9B62',
        ];

        foreach ($uniqueIndexes as $table => $indexName) {
            $this->addSql(sprintf('CREATE TABLE %s (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))', $table));
            $this->addSql(sprintf('CREATE UNIQUE INDEX %s ON %s (slug)', $indexName, $table));
        }

        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, media_type_id INT DEFAULT NULL, name VARCHAR(140) NOT NULL, slug VARCHAR(140) NOT NULL, language VARCHAR(10) DEFAULT NULL, is_interest_related BOOLEAN NOT NULL, is_auto_generated BOOLEAN NOT NULL, is_active BOOLEAN NOT NULL, confidence INT DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_389B783A49B0ADA ON tag (media_type_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_389B783989D9B62 ON tag (slug)');
        $this->addSql('ALTER TABLE tag ADD CONSTRAINT FK_389B783EA9A0F6B9 FOREIGN KEY (media_type_id) REFERENCES media_type_reference (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE review ADD is_draft BOOLEAN DEFAULT FALSE NOT NULL');
        $this->addSql('ALTER TABLE review ADD is_auto_created BOOLEAN DEFAULT FALSE NOT NULL');
        $this->addSql('ALTER TABLE review ALTER is_draft DROP DEFAULT');
        $this->addSql('ALTER TABLE review ALTER is_auto_created DROP DEFAULT');

        $this->seedReferences();
        $this->migrateDetectedTags();
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE tag DROP CONSTRAINT FK_389B783EA9A0F6B9');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE media_type_reference');
        $this->addSql('DROP TABLE source_type_reference');
        $this->addSql('DROP TABLE fetch_mode_reference');
        $this->addSql('DROP TABLE decision_type_reference');
        $this->addSql('DROP TABLE clickbait_level_reference');
        $this->addSql('DROP TABLE analysis_language_reference');
        $this->addSql('ALTER TABLE review DROP is_draft');
        $this->addSql('ALTER TABLE review DROP is_auto_created');
    }

    private function seedReferences(): void
    {
        $now = 'CURRENT_TIMESTAMP';
        $this->insertValues('media_type_reference', [
            'video_game' => 'Jeu video',
            'book' => 'Livre',
            'science_fiction_novel' => 'Roman SF',
            'fantasy_novel' => 'Roman fantasy',
            'space_opera_novel' => 'Space opera',
            'bd' => 'BD',
            'manga' => 'Manga',
            'manhwa' => 'Manhwa',
            'manhua' => 'Manhua',
            'comics' => 'Comics',
            'comic' => 'BD / manga / comics',
            'anime' => 'Anime',
            'movie' => 'Film',
            'series' => 'Serie',
            'ttrpg' => 'JDR',
            'figurines' => 'Figurines',
            'other' => 'Autre',
        ], $now);
        $this->insertValues('source_type_reference', [
            'website' => 'Site web',
            'rss' => 'Flux RSS',
            'newsletter' => 'Newsletter',
            'youtube' => 'YouTube',
            'podcast' => 'Podcast',
            'social' => 'Reseau social',
            'other' => 'Autre',
        ], $now);
        $this->insertValues('fetch_mode_reference', ['manual' => 'Manuel', 'rss' => 'RSS'], $now);
        $this->insertValues('decision_type_reference', ['relevant' => 'Pertinent', 'maybe_relevant' => 'A verifier', 'ignored' => 'Ignore', 'clickbait' => 'Putaclic'], $now);
        $this->insertValues('clickbait_level_reference', ['clean' => 'Clean', 'suspicious' => 'Suspect', 'clickbait' => 'Putaclic'], $now);
        $this->insertValues('analysis_language_reference', ['fr' => 'Francais', 'en' => 'Anglais', 'mixed' => 'Mixte', 'unknown' => 'Inconnue'], $now);
    }

    /**
     * @param array<string, string> $values
     */
    private function insertValues(string $table, array $values, string $now): void
    {
        foreach ($values as $slug => $name) {
            $this->addSql(sprintf(
                "INSERT INTO %s (name, slug, is_active, created_at, updated_at) VALUES (%s, %s, TRUE, %s, %s)",
                $table,
                $this->quote($name),
                $this->quote($slug),
                $now,
                $now,
            ));
        }
    }

    private function migrateDetectedTags(): void
    {
        $this->addSql("
            INSERT INTO tag (name, slug, language, media_type_id, is_interest_related, is_auto_generated, is_active, confidence, notes, created_at, updated_at)
            SELECT DISTINCT
                initcap(replace(tag_slug, '-', ' ')),
                tag_slug,
                NULL,
                NULL::INT,
                tag_slug IN ('sf', 'science-fiction', 'fantasy', 'space-opera', 'cyberpunk', 'jeu-video', 'manga', 'bd', 'comics', 'jdr', 'figurines', 'battlefield', 'final-fantasy', 'warhammer-40k'),
                FALSE,
                TRUE,
                80,
                'Migre depuis detected_tags existants.',
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            FROM (
                SELECT json_array_elements_text(detected_tags) AS tag_slug
                FROM entry
                WHERE detected_tags IS NOT NULL
            ) AS existing_tags
            WHERE tag_slug <> ''
            ON CONFLICT (slug) DO NOTHING
        ");
    }

    private function quote(string $value): string
    {
        return "'".str_replace("'", "''", $value)."'";
    }
}
