<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260503170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add synthesis reports and link them to entries';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE synthesis_report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, from_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, to_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, notes TEXT DEFAULT NULL, format VARCHAR(30) NOT NULL, generated_content TEXT DEFAULT NULL, include_maybe_relevant BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE synthesis_report_entry (synthesis_report_id INT NOT NULL, entry_id INT NOT NULL, PRIMARY KEY(synthesis_report_id, entry_id))');
        $this->addSql('CREATE INDEX IDX_38E7A063BC6545F9 ON synthesis_report_entry (synthesis_report_id)');
        $this->addSql('CREATE INDEX IDX_38E7A063BA364942 ON synthesis_report_entry (entry_id)');
        $this->addSql('ALTER TABLE synthesis_report_entry ADD CONSTRAINT FK_38E7A063BC6545F9 FOREIGN KEY (synthesis_report_id) REFERENCES synthesis_report (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE synthesis_report_entry ADD CONSTRAINT FK_38E7A063BA364942 FOREIGN KEY (entry_id) REFERENCES entry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE entry ADD last_synthesized_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE synthesis_report_entry DROP CONSTRAINT FK_38E7A063BC6545F9');
        $this->addSql('ALTER TABLE synthesis_report_entry DROP CONSTRAINT FK_38E7A063BA364942');
        $this->addSql('DROP TABLE synthesis_report_entry');
        $this->addSql('DROP TABLE synthesis_report');
        $this->addSql('ALTER TABLE entry DROP last_synthesized_at');
    }
}
