<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260502160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Source, Entry and Review tables for V1.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, type VARCHAR(255) NOT NULL, url VARCHAR(500) DEFAULT NULL, is_active BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, source_id INT NOT NULL, title VARCHAR(255) NOT NULL, media_type VARCHAR(255) NOT NULL, author_or_studio VARCHAR(255) DEFAULT NULL, original_url VARCHAR(500) DEFAULT NULL, raw_content TEXT DEFAULT NULL, spotted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, interest_level INT NOT NULL, status VARCHAR(255) NOT NULL, personal_tags JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2B219D70F675F31B ON entry (source_id)');
        $this->addSql('CREATE TABLE review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entry_id INT NOT NULL, summary TEXT DEFAULT NULL, strengths TEXT DEFAULT NULL, weaknesses TEXT DEFAULT NULL, personal_note TEXT DEFAULT NULL, verdict VARCHAR(255) NOT NULL, score INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_794381CABA364942 ON review (entry_id)');
        $this->addSql('ALTER TABLE entry ADD CONSTRAINT FK_2B219D70F675F31B FOREIGN KEY (source_id) REFERENCES source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381CABA364942 FOREIGN KEY (entry_id) REFERENCES entry (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381CABA364942');
        $this->addSql('ALTER TABLE entry DROP CONSTRAINT FK_2B219D70F675F31B');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE entry');
        $this->addSql('DROP TABLE source');
    }
}
