<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260504130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add administrable interest profile rules and source profile fields';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE interest_profile_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(40) NOT NULL, value VARCHAR(180) NOT NULL, weight VARCHAR(20) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_INTEREST_PROFILE_RULE_CATEGORY ON interest_profile_rule (category)');
        $this->addSql('ALTER TABLE source ADD source_profile VARCHAR(40) DEFAULT NULL');
        $this->addSql("ALTER TABLE source ADD source_weight VARCHAR(20) DEFAULT 'normal' NOT NULL");
        $this->addSql("ALTER TABLE source ALTER source_weight DROP DEFAULT");
        $this->seedRules();
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE interest_profile_rule');
        $this->addSql('ALTER TABLE source DROP source_profile');
        $this->addSql('ALTER TABLE source DROP source_weight');
    }

    private function seedRules(): void
    {
        $rules = [
            ['preferred_media', 'jeu video', 'normal'],
            ['preferred_media', 'livre', 'normal'],
            ['preferred_media', 'bd', 'normal'],
            ['preferred_media', 'manga', 'normal'],
            ['preferred_media', 'jdr', 'normal'],
            ['positive_keyword', 'science-fiction', 'high'],
            ['positive_keyword', 'fantasy', 'high'],
            ['positive_keyword', 'space opera', 'high'],
            ['license', 'warhammer 40k', 'high'],
            ['license', 'final fantasy', 'normal'],
            ['license', 'battlefield', 'normal'],
            ['studio', 'games workshop', 'normal'],
            ['studio', 'square enix', 'normal'],
            ['negative_keyword', 'people', 'normal'],
            ['negative_keyword', 'drama', 'normal'],
            ['negative_keyword', 'concours', 'normal'],
            ['excluded_phrase', 'rumeur people', 'high'],
        ];

        foreach ($rules as [$category, $value, $weight]) {
            $this->addSql(sprintf(
                "INSERT INTO interest_profile_rule (category, value, weight, is_active, created_at, updated_at) VALUES ('%s', %s, '%s', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                $category,
                $this->quote($value),
                $weight,
            ));
        }
    }

    private function quote(string $value): string
    {
        return "'".str_replace("'", "''", $value)."'";
    }
}
