<?php

namespace App\Service;

use App\Entity\Entry;
use App\Entity\MediaTypeReference;
use App\Entity\Tag;
use App\Repository\TagRepository;
use Doctrine\ORM\EntityManagerInterface;

class AutoTagEnricher
{
    /**
     * @var array<string, true>
     */
    private array $scheduledSlugs = [];

    public function __construct(
        private readonly TagRepository $tagRepository,
        private readonly EntityManagerInterface $entityManager,
        private readonly Slugger $slugger,
    ) {
    }

    /**
     * Auto-creation prudente : un tag inconnu n'est cree que si le contexte est
     * deja qualifie par plusieurs signaux convergents.
     *
     * @param array<int, string> $candidateLabels
     */
    public function enrich(Entry $entry, array $candidateLabels): int
    {
        $knownRelevantTags = 0;
        foreach ($entry->getDetectedTags() as $slug) {
            $tag = $this->tagRepository->findOneBySlug($slug);
            if ($tag instanceof Tag && $tag->isActive() && $tag->isInterestRelated()) {
                ++$knownRelevantTags;
            }
        }

        $signals = 0;
        $signals += $entry->getDetectedMediaType() !== null ? 1 : 0;
        $signals += count($entry->getMatchedPositiveKeywords()) > 0 ? 1 : 0;
        $signals += $knownRelevantTags > 0 ? 1 : 0;
        $signals += ($entry->getRelevanceScore() ?? 0) >= 45 ? 1 : 0;

        if ($signals < 3) {
            return 0;
        }

        $created = 0;
        foreach ($candidateLabels as $label) {
            $slug = $this->slugger->slug($label);
            if ($slug === '' || strlen($slug) < 3 || isset($this->scheduledSlugs[$slug]) || $this->tagRepository->findOneBySlug($slug) instanceof Tag) {
                continue;
            }

            $tag = (new Tag())
                ->setName($label)
                ->setSlug($slug)
                ->setIsAutoGenerated(true)
                ->setIsInterestRelated(false)
                ->setIsActive(false)
                ->setConfidence(min(100, 50 + ($signals * 10)))
                ->setMediaType($this->findMediaTypeReference($entry))
                ->setLanguage($entry->getAnalysisLanguage())
                ->setNotes('Cree automatiquement depuis les categories/tags RSS. A valider avant usage actif.');

            $this->entityManager->persist($tag);
            $this->scheduledSlugs[$slug] = true;
            ++$created;
        }

        return $created;
    }

    private function findMediaTypeReference(Entry $entry): ?MediaTypeReference
    {
        $mediaType = $entry->getDetectedMediaType();
        if ($mediaType === null) {
            return null;
        }

        $reference = $this->entityManager->getRepository(MediaTypeReference::class)->findOneBy(['slug' => $mediaType->value]);

        return $reference instanceof MediaTypeReference ? $reference : null;
    }
}
