<?php

namespace App\Form;

use App\Entity\MediaTypeReference;
use App\Entity\Tag;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TagType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, ['label' => 'Nom'])
            ->add('slug', TextType::class, ['label' => 'Slug'])
            ->add('language', ChoiceType::class, [
                'label' => 'Langue',
                'required' => false,
                'choices' => [
                    'Francais' => 'fr',
                    'Anglais' => 'en',
                    'Mixte' => 'mixed',
                    'Inconnue' => 'unknown',
                ],
            ])
            ->add('mediaType', EntityType::class, [
                'label' => 'Media associe',
                'class' => MediaTypeReference::class,
                'choice_label' => 'name',
                'required' => false,
            ])
            ->add('isInterestRelated', CheckboxType::class, [
                'label' => "Lie a mes centres d'interet",
                'required' => false,
            ])
            ->add('isAutoGenerated', CheckboxType::class, [
                'label' => 'Cree automatiquement',
                'required' => false,
            ])
            ->add('isActive', CheckboxType::class, [
                'label' => 'Actif',
                'required' => false,
            ])
            ->add('confidence', IntegerType::class, [
                'label' => 'Confiance',
                'required' => false,
                'attr' => ['min' => 0, 'max' => 100],
            ])
            ->add('notes', TextareaType::class, [
                'label' => 'Notes',
                'required' => false,
                'attr' => ['rows' => 4],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tag::class,
        ]);
    }
}
